config/routes.rb
Rails.application.routes.draw do

  resources :comics

  root to: 'comics#index'

end

app/models/comic.rb
class Comic < ActiveRecord::Base
  validates :artist, presence: true
  validates :author, presence: true
  validates :cover_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :issue_number, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :publisher, presence: true
  validates :title, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  def index
    #random line for a test
    @comics = Comic.all
  end

  def show
  end

  def new
    @comic = Comic.new
  end

  def edit
  end

  def create
    @comic = Comic.new(comic_params)

    if @comic.save
      redirect_to @comic, notice: 'Comic was successfully created.'
    else
      render :new
    end
  end

  def update
    if @comic.update(comic_params)
      redirect_to @comic, notice: 'Comic was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comic.destroy
    redirect_to comics_url, notice: 'Comic was successfully destroyed.'
  end

  private

  def set_comic
    @comic = Comic.find(params[:id])
  end

  def comic_params
    params.require(:comic).permit(:title, :issue_number, :year, :printing, :publisher, :author, :artist, :cover_price, :cover_variant, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :issue_number %><br>
    <%= f.text_field :issue_number %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :printing %><br>
    <%= f.number_field :printing %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :cover_price %><br>
    <%= f.text_field :cover_price %>
  </div>
  <div class="field">
    <%= f.label :cover_variant %><br>
    <%= f.text_field :cover_variant %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<h1>Listing Comics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Issue number</th>
      <th>Year</th>
      <th>Printing</th>
      <th>Publisher</th>
      <th>Author</th>
      <th>Artist</th>
      <th>Cover price</th>
      <th>Cover variant</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comics.each do |comic| %>
      <tr>
        <td><%= comic.title %></td>
        <td><%= comic.issue_number %></td>
        <td><%= comic.year %></td>
        <td><%= comic.printing %></td>
        <td><%= comic.publisher %></td>
        <td><%= comic.author %></td>
        <td><%= comic.artist %></td>
        <td><%= comic.cover_price %></td>
        <td><%= comic.cover_variant %></td>
        <td><%= comic.description %></td>
        <td><%= link_to 'Show', comic %></td>
        <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
        <td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comic', new_comic_path %>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @comic.title %>
</p>

<p>
  <strong>Issue number:</strong>
  <%= @comic.issue_number %>
</p>

<p>
  <strong>Year:</strong>
  <%= @comic.year %>
</p>

<p>
  <strong>Printing:</strong>
  <%= @comic.printing %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @comic.publisher %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comic.author %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @comic.artist %>
</p>

<p>
  <strong>Cover price:</strong>
  <%= @comic.cover_price %>
</p>

<p>
  <strong>Cover variant:</strong>
  <%= @comic.cover_variant %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comic.description %>
</p>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LongBox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='flash-messages'>
    <% flash.each do |key,message| %>
      <div class="flash-message <%= key %>"><%= message %></div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>